### ISSUE TITLE
Breaking Change with Nextjs 11

### ISSUE THREAD

**Issue by RealPresidentlin** [adamsoffer/next-apollo#101]
So the next version of Nextjs 11, has a breaking change with Head.Rewind().

[link to breaking change](https://nextjs.org/docs/upgrading#remove-headrewind)

This mostly affects withApollo.tsx

I'm pretty sure there is a plan to upgrade next-apollo, just figured I would let you know.

**Comment by adamsoffer** [comment]
Closed by #102
