### ISSUE TITLE
Breaking: v5.0.5 lacks `dist` folder

### ISSUE THREAD

**Issue by divanc** [adamsoffer/next-apollo#103]
It seems, last version `v5.0.5` doesn't have `dist` folder. Thus, version is not working at all. 

Changelog didn't seem to have any breakable changes, so, I guess, the problem has occurred while publishing

![image](https://user-images.githubusercontent.com/16625670/123424752-ed38d680-d5c9-11eb-8a40-195f881b1a98.png)

![image](https://user-images.githubusercontent.com/16625670/123425296-a7c8d900-d5ca-11eb-88e4-4bd7250af1f9.png)

**Comment by adamsoffer** [comment]
@Betra apologies. Publishing again now.

**Comment by adamsoffer** [comment]
Indeed, failed to build before publishing 🤦‍♂️. I just published `v5.0.6`.
