### ISSUE TITLE
Outdated next.js peer dependency

### ISSUE THREAD

**Issue by abir-taheer** [adamsoffer/next-apollo#106]
Tried to manually update my next.js version to 11.1.0 because of a vulnerability but next-apollos throws an error when running `rpm install`

> npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: next-apollo@5.0.6
npm ERR! Found: next@11.1.0
npm ERR! node_modules/next
npm ERR!   next@"11.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer next@"^9.3.6 || ^10.0.0" from next-apollo@5.0.6
npm ERR! node_modules/next-apollo
npm ERR!   next-apollo@"^5.0.6" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: next@10.2.3
npm ERR! node_modules/next
npm ERR!   peer next@"^9.3.6 || ^10.0.0" from next-apollo@5.0.6
npm ERR!   node_modules/next-apollo
npm ERR!     next-apollo@"^5.0.6" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps

The issue goes away when I run with `npm install --legacy-peer-deps` but that's not an ideal solution. It'd be great if the package could be updated to support next 11 as a peer dependency alongside next 9 and 10

**Comment by adamsoffer** [comment]
Hey @abir-taheer - heads up next has been updated to v11 in the latest release. Thanks for reporting.
