### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by couturecraigj** [adamsoffer/next-apollo#11]
I was having issues with SSR until I identified what was causing it by digging through your code.  You may want to update the readme to tell people not to initialize the cache on their own if that want the SSR to work.

**Comment by adamsoffer** [comment]
Thanks for bringing this to my attention 👍 Do you mind elaborating on the disclaimer you'd like to see added? I can add it to the README if you drop it in here. Or happy to merge a pull request.

**Comment by couturecraigj** [comment]
Awesome.  I am in the middle of traveling but will get back to you when I am able.

**Comment by razor-x** [comment]
@ads1018 On a related note, I would like to use this with the [fragment matcher](https://github.com/apollographql/apollo-client/blob/master/docs/source/recipes/fragment-matching.md). I can submit a PR with docs + something like

```js
function create(apolloConfig, initialState) {
  const createCache = apolloConfig.createCache || () => new InMemoryCache()
  return new ApolloClient({
    connectToDevTools: process.browser,
    ssrMode: !process.browser, // Disables forceFetch on the server (so queries are only run once)
    cache: createCache().restore(initialState || {}),
    ...apolloConfig // then omit apolloConfig.createCache
  })
}

This ways users can control how the cache is created, but not when.
```

**Comment by adamsoffer** [comment]
@razor-x that would be great!
