### ISSUE TITLE
Could not resolve dependency for graphql@16.2.0

### ISSUE THREAD

**Issue by han109k** [adamsoffer/next-apollo#115]
![Screenshot from 2022-01-23 14-24-42](https://user-images.githubusercontent.com/48852389/150676172-0dc98701-85dc-4d39-b509-c1b0ee599b48.png)
^15.0.0 should work with 16.2.0? It would be great if you could update the dependency for GraphQL. Thanks in advance.

**Comment by rimsila** [comment]
I'm using yarn working

**Comment by han109k** [comment]
For my case, removed package-lock.json and /node_modules. `yarn install` builds and installs dependencies without any errors.
