### ISSUE TITLE
Direct Cache access

### ISSUE THREAD

**Issue by verzil** [adamsoffer/next-apollo#14]
Hey I'm wondering do we still have the capabilities of directly reading/writing to the apollo cache. Since the module gives a HOC, I don't actually know where the apollo instance sits.

Any help is deeply appreciated

**Comment by adamsoffer** [comment]
Hey @verzil,

@razor-x recently submitted a [pull request](#13) that allows you to use a custom cache. Documented [here](https://github.com/ads1018/next-apollo#custom-cache). Is this what you're looking for?

**Comment by verzil** [comment]
@adamsoffer i was looking for a way to get hold of the apollo instance.
I found that react-apollo has a WithApollo HOC that gives you the client object.

A little off topic here, I'm running into a problem that when server side rendering with apollo. The page would be rendered before the data is arrived. I'm not really sure how to wait for data to be fetched by apollo first before responding. could you help me out?
