### ISSUE TITLE
Expose entirety of req and not just headers

### ISSUE THREAD

**Issue by jupl** [adamsoffer/next-apollo#15]
I am trying to do server side rendering support using `apollo-link-schema` server-side for [reasons](https://www.apollographql.com/docs/react/features/server-side-rendering.html#local-queries). To do that I need to build the context which is currently dependent on the `req` HTTP request object. Unfortunately I am unable to do that with the `config` function argument as I'm only given headers. The library is much more flexible if more things are exposed like [`next-redux-wrapper`](https://github.com/kirill-konshin/next-redux-wrapper/blob/8d68482deb4590bf3eb461ce7f2c5c3c1a314482/src/index.js#L139).

I can do a PR if interested.

**Comment by adamsoffer** [comment]
Hey @jupl - yeah that makes sense. A PR would be more than welcome!
