### ISSUE TITLE
Is my example correct ?

### ISSUE THREAD

**Issue by yann-yinn** [adamsoffer/next-apollo#18]
Hello ! This is how i use next-apollo, wrapping each page with withData Hoc, can you confirm this is the correct way ?  

https://github.com/nyl-auster/reactpress-graphql/blob/a5d70ee81760688a3af3c27b854307e28bf2b0a2/pages/post.js

I was expecting to be required to create a __app.js_ file and wrapping my whole app with something like , which seems to be unnecessary with your Hoc.
```js  <ApolloProvider client={client}>```

Are your passing ApolloProvider to every component implementing withData ?

**Comment by adamsoffer** [comment]
Hey @nyl-auster - there are two ways you can go about it.

1. You can use the HOC on a page-by-page basis which is what this library is for (some pages may be static and may not need apollo). Check out [this example](https://github.com/adamsoffer/next-apollo-example)
2. Or you can wrap every page automatically by using the new `<App>` component provided by next. Check out [this example](https://github.com/zeit/next.js/tree/canary/examples/with-apollo)

**Comment by yann-yinn** [comment]
@adamsoffer thanks !
