### ISSUE TITLE
Eliminating Apollo in the production bundle

### ISSUE THREAD

**Issue by stevenpetryk** [adamsoffer/next-apollo#20]
This is a request for discussion, not a feature request or a bug.

Side-note: this is a fantastic library for using GraphQL with NextJS. Thanks so much for it.

I'm wondering, when server-rendering a site (or statically exporting it), we don't really _need_ all of the Apollo stuff on the client side. All of the data is prefetched. So this technically means that we don't need Apollo at runtime, only on the server side.

BUT, of course, there are `<Query>`s all throughout the React app. This means that we can't simply make Apollo a [server-only module](https://arunoda.me/blog/ssr-and-server-only-modules). This is kind of a bummer since `react-apollo` and `apollo-client` are not small.

I was hoping to open up some discussion on how this could be mitigated—namely, I'm thinking I'll try to understand how this library stores the extracted client cache and makes it available to child `<Query>`s. Maybe it would be possible to use a webpack plugin to swap out `react-apollo` at build time and replace it with a dumb stubbed out version that expects data to be provided by NextJS?

**Comment by millette** [comment]
Server-side only handles the first load. When you follow a link, client-side handles rendering.

**Comment by stevenpetryk** [comment]
Going to close this out since it does not seem to be leading to any discussion.
