### ISSUE TITLE
Is the graphql server URI required to be absolute?

### ISSUE THREAD

**Issue by bogas04** [adamsoffer/next-apollo#21]
The [apollo-link-http](https://www.apollographql.com/docs/link/links/http.html#passing-context) API doesn't seem to indicate that, so is it a `next-apollo` requirement?

**Comment by adamsoffer** [comment]
Hey @bogas04 - it depends whether your graphql api is on a remote server or not. In the example I'm using, the graphql api is remote which is why I'm using an absolute uri. If you're running your next application on the same server as your api then you can use a relative uri.

**Comment by adamsoffer** [comment]
I'll remove that comment from the docs. I can see how that's confusing. Thanks for pointing that out!

**Comment by bogas04** [comment]
Hi @adamsoffer, yeah that's what I was thinking, however the comment in the README implies that you can't give a relative URI whatsoever.


Bad timing haha. Thank you so much!

**Comment by adamsoffer** [comment]
@bogas04 yeah good looks. Just removed that from the comments. Thank you!
