### ISSUE TITLE
Remove deprecated apollo-client-present package in favor of apollo-boost

### ISSUE THREAD

**Issue by chiedo** [adamsoffer/next-apollo#23]
Hey my man!

I'm having issues with Apollo Dev Tools and I'm wondering if it's because you're using the deprecated https://www.npmjs.com/package/apollo-client-preset package.

Not sure but either way, you may want to upgrade to https://www.npmjs.com/package/apollo-boost

I can submit a PR if you want but sounds pretty straight forward.

Just let me know if you'd rather I handle the upgrade.

Thanks for this package!

**Comment by adamsoffer** [comment]
Yo! Ah yes, good spot thanks for pointing that out. If you could submit a PR that would be awesome!
