### ISSUE TITLE
Next v8+ breaks Data Prefetching

### ISSUE THREAD

**Issue by adamsoffer** [adamsoffer/next-apollo#26]

**Comment by resdevd** [comment]
@adamsoffer Thanks for your amazing work. I'm just learning graphql with a next & react personal project. I'm having issues with Nextjs withApollo example. I'd like to try your next-apollo approach. however I'm just curious if this bug impacts the core functioning? Or if it just affects some other functionality other than core graphql fetching. Thanks

**Comment by adamsoffer** [comment]
Thanks @resdevd ! I just double checked and seems as though using this with v8.0 breaks ~SSR~ data prefetching but doesn't impact anything else. I'll investigate as soon as I'm able.

**Comment by resdevd** [comment]
@adamsoffer Thank you. Once again appreciate your library with next and apollo.

**Comment by samuelcastro** [comment]
Any update on this?

**Comment by flippidippi** [comment]
Has anyone gotten this to work?

**Comment by mstn** [comment]
@adamsoffer I do not know if it is related, but is it possible to use the apollo client in `getStaticPaths`?

**Comment by adamsoffer** [comment]
Removed support for data prefetching in light of all the great work Next has done with incremental static builds.
