### ISSUE TITLE
Exact versions in package.json causing duplicate react installs?

### ISSUE THREAD

**Issue by AndrewRayCode** [adamsoffer/next-apollo#28]
I have two versions of React on my page, breaking context. One of them seems to be coming from this library:

```bash
/app # cat node_modules/next-apollo/node_modules/react/package.json | grep version
    "type": "version",
  "version": "16.8.2"
```

I suspect, but don't know for sure, that it's happening because my locally installed version for Next.js `16.8.4` doesn't satisfy the exact dep in this package: https://github.com/adamsoffer/next-apollo/blob/master/package.json#L60

It looks like the semver for this type of package should specify `>=` instead of exact?

**Comment by adamsoffer** [comment]
Resolved by #36
