### ISSUE TITLE
Support Auth Integration

### ISSUE THREAD

**Issue by adamsoffer** [adamsoffer/next-apollo#3]

**Comment by nickredmark** [comment]
Hey there, I have basically the same package (updating today to apollo 2) and it handles credentials, check it out here: https://github.com/nmaro/ooth/tree/master/packages/ooth-client-react-next-apollo

**Comment by adamsoffer** [comment]
Thanks @nmaro ! I've also been looking at the official apollo-auth example in the next.js examples directory for inspiration. The challenge is how configurable to make it.

**Comment by thealjey** [comment]
see #5 for an example set up
I could make a complete working (simple) example implementation of authentication, if you want

**Comment by adamsoffer** [comment]
Yes please!

**Comment by thealjey** [comment]
@ads1018 [next-apollo-auth-example](https://github.com/thealjey/next-apollo-auth-example)
tried to keep it as simple as possible, as such there's no subscriptions or dataloaders etc...

**Comment by adamsoffer** [comment]
@thealjey this is brilliant. Super helpful. I can add a link to your example in the project's README. Thank you! 🙏

**Comment by thealjey** [comment]
I'm not sure if that was a question or not (there's no question mark) 😃 
if so, yes, sure you can add a link
the example repo will stay for as long as necessary
