### ISSUE TITLE
Dependency on next-server

### ISSUE THREAD

**Issue by AndrewRayCode** [adamsoffer/next-apollo#30]
I'm not fully up to speed on the guts of next, but I'm using a custom express server with my next app. Installing next-server just to get `execOnce` seems like a lot? Context: I (apparently ) don't have next-server installed locally so when I changed next to a peerdependency in my fork of this project, and installed my fork locally, it didn't work.

**Comment by adamsoffer** [comment]
Yeah, we should definitely remove that dependency. Thanks for pointing this out!

**Comment by adamsoffer** [comment]
This dep has been removed as of `v3.1.2`
