### ISSUE TITLE
Installing react as a dependency causes Invalid Hook Call Warning

### ISSUE THREAD

**Issue by Hilaryous** [adamsoffer/next-apollo#35]
This is related to #28. I believe listing react as a dependency is causing this issue within my application: https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react

At the very least `react` and `react-dom should be listed as peer dependencies to prevent this and possibly other issues from happening.

**Comment by adamsoffer** [comment]
Thanks for the PR :)
