### ISSUE TITLE
Integrate with new @apollo/react-hooks

### ISSUE THREAD

**Issue by adamsoffer** [adamsoffer/next-apollo#37]

**Comment by adamsoffer** [comment]
If anyone is interested, you can now use [apollo hooks](https://www.npmjs.com/package/@apollo/react-hooks) with this library :) `npm install --save next-apollo@beta`

**Comment by DavoCg** [comment]
Hi @adamsoffer thanks for that ! I'll give a try, it could be interesting to have a minimalistic example project with next-apollo and apollo hooks !

**Comment by DavoCg** [comment]
Hi @adamsoffer I give a try to ```next-apollo@beta``` and I have this error ```Cannot read property 'apollo' of undefined``` and I think it comes from here : https://github.com/adamsoffer/next-apollo/blob/73a9ca0729b20ee738db4465436e75af29242291/src/withData.js#L72 

I'll continue trying to make it works.

I could be interesting to have a working example with ```next-apollo@beta``` and ``` @apollo/react-hooks```

**Comment by adamsoffer** [comment]
Hey @DavoCg - I actually just updated the `next-apollo-example` repo to use `next-apollo@beta` if you wanna have a look there :)

https://github.com/adamsoffer/next-apollo-example
