### ISSUE TITLE
useSubscription hook not working properly

### ISSUE THREAD

**Issue by brunocrosier** [adamsoffer/next-apollo#43]
Hey Adam,

I'm trying to port over the [@apollo/react-hooks demo ](https://codesandbox.io/s/5v1ol0nkjx)from React to Next.js using your library and came across this..

Here is my [CodeSandbox](https://codesandbox.io/s/apolloreact-hooks-nextjs-wkk1e). `useQuery` and `useMutation` seem to be working perfectly, but `useSubscription` will return the value of "data" as undefined (althought "loading" seems to be correct)

Any idea what might be the cause of this?

**Comment by adamsoffer** [comment]
hmm it seems to be working for me. I saw a "loading" indicator but after 5 seconds or so it resolved. Are you seeing any errors?

![image](https://user-images.githubusercontent.com/555740/60198903-b11edf80-9810-11e9-9902-60580a823f46.png)

**Comment by adamsoffer** [comment]
The latest news is not rendering server side though if that's what you mean.

**Comment by brunocrosier** [comment]
Sorry I think my explanation was vague :)

Please check my updated [CodeSandbox version](https://codesandbox.io/s/apolloreact-hooks-nextjs-wkk1e) again

You should see now that it will initially show a "loading" and then it will error out because "data" is undefined

Here is the functional component in question:

```javascript
export function LatestNews() {
  const { loading, data } = useSubscription(LATEST_NEWS);
  return (
    <Card className="bg-light">
      <CardBody>
        <CardTitle>
          <h5>Latest News</h5>
        </CardTitle>
        <CardText>{loading ? "Loading..." : data.latestNews.content}</CardText>
      </CardBody>
    </Card>
  );
}
```

so the useSubscription hook is creating `const loading` and `const data` and `loading` works properly but `data` returns "undefined"

you can see this in a [slightly modified version of my CodeSandbox](https://codesandbox.io/s/apolloreact-hooks-nextjs-e0p1i) which just `console.log`s the value of `useSubscription(LATEST_NEWS)` (note, here I commented out the <CardText /> component which was causing the error

Here you should see in the console:

```javascript
useSubscription is:  { loading: true,
  error: undefined,
  data: undefined,
  variables: undefined }
```

essentially, the problem seems to be that useSubscription returns `data: undefined`, which is not what we want :)

**Comment by brunocrosier** [comment]
ignore the above! i realized that i forgot add a websocket link so of course it wouldn't work :)

however, there is nothing in the next-apollo docs about subscriptions - are they supported? if so, what would the setup look like?
