### ISSUE TITLE
Data prefetch when changing pages

### ISSUE THREAD

**Issue by mrphilipandrews** [adamsoffer/next-apollo#54]
Is it possible to pre-fetch the data from the queries before the page does a client side render?
Prefetching seems to work fine for SSR but i if transition to another page the graphql queries run after the next page render.

I noticed this didnt happen with https://github.com/lfades/next-with-apollo 
The behaviour there is: click on link, query requested and completes, then the page transitions and the next page is rendered with the data.

**Comment by adamsoffer** [comment]
@fatlinesofcode I just published `v3.1.4` so it's now more in line with what's in the [official example](https://github.com/zeit/next.js/blob/canary/examples/with-apollo/lib/apollo.js). Can you confirm it behaves in the same way now?

**Comment by mrphilipandrews** [comment]
hi @adamsoffer thanks for the follow up, but we've decided to run apollo at the _app level now instead.
