### ISSUE TITLE
Using this with getInitialProps() in pages

### ISSUE THREAD

**Issue by hobbs** [adamsoffer/next-apollo#6]
The examples I've seen that use this library avoid using getInitialProps() in the page components, whereas the learnnextjs.com prefers doing that and then passing data into child components.

Is the recommendation to always use apollo in components and not pages? How does one use `withData` and `graphql` together?

**Comment by hobbs** [comment]
Actually, I did get this to work fine in a page js via
```
export default compose(
    withData,
    graphql(query, {options: queryOptions}))(Event)
```

I think I was fighting another issue ( https://github.com/zeit/next.js/issues/3234 )

**Comment by Ponjimon** [comment]
@hobbs may I have an example of how you got getInitialProps to work?
