### ISSUE TITLE
Typescript support?

### ISSUE THREAD

**Issue by samuelcastro** [adamsoffer/next-apollo#66]
Do you have TS support?

Thanks.

**Comment by lednhatkhanh** [comment]
Hello, any updates on this, I also would like to use this library with typescript

**Comment by lednhatkhanh** [comment]
@samuelcastro If I have time this weekend then I will make a PR for providing typescript declaration file for this.

**Comment by adamsoffer** [comment]
@lednhatkhanh Been meaning to rewrite this in typescript. A PR would be awesome and I'm sure many in the community would really appreciate it. Feel free to convert the files typescript.

**Comment by dotansimha** [comment]
Any update on this one? 
Thanks :)

**Comment by adamsoffer** [comment]
Closing in favor of #71.
