### ISSUE TITLE
New release: apollo-client v3

### ISSUE THREAD

**Issue by qathom** [adamsoffer/next-apollo#78]
Hi @adamsoffer 

Thanks for creating `next-apollo`!
I just opened a [pull request](https://github.com/adamsoffer/next-apollo/pull/77) to support **apollo-client v3**.

This allows us to use `next-apollo`with this new release and avoid this kind of error:

Module not found: Error: Can't resolve '@apollo/react-ssr' in '/Users/ameizoso/Workspaces/Logitech/etail-platform/node_modules/next-apollo/dist'

React Apollo’s SSR utilities (like getDataFromTree, getMarkupFromTree, and renderToStringWithData) are included in the @apollo/client package. Access them via @apollo/client/react/ssr:

**Comment by adamsoffer** [comment]
PR merged and v5.0.0 published! Thanks @qathom !
