### ISSUE TITLE
Can we have an access to context ctx in apolloClient ?

### ISSUE THREAD

**Issue by ghost** [adamsoffer/next-apollo#82]
Hi, 
i need to send cookie from nextjs to backend, would be nice if we have access to ctx in apolloClient function when ssr is true.

**Comment by adamsoffer** [comment]
Hey @zarghamkhandev - the project was recently converted to typescript and I believe you now have access to ctx https://github.com/adamsoffer/next-apollo/blob/master/src/withApollo.tsx#L218

Let me know if this is still an issue.

**Comment by lukel97** [comment]
@adamsoffer are we supposed to copy over this module ourselves and edit `createApolloClient` to do what we need with the context object?

**Comment by adamsoffer** [comment]
Closed by #83
